SUPABASE_URL = "https://dkfvwjxmrirclgbmoehl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZnZ3anhtcmlyY2xnYm1vZWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTEzMDAsImV4cCI6MjA1ODI4NzMwMH0.cjo2Eecsr05vnbib37YQakx-H0r--OF3iMUP20EvGdY"
